### ISSUE TITLE
[BUG] Erro quando não tem telefone cadastrado na empresa

### ISSUE THREAD

**Issue by marcelsavegnago** [erpbrasil/erpbrasil.edoc.pdf#5]
Este problema foi identificado nos testes de geração da NFe com o Odoo. No caso foi um teste ao acaso com uma empresa sem telefone cadastrado.

File "/odoo-lab/venv37/lib/python3.8/site-packages/erpbrasil/edoc/pdf/danfe_formata.py", line 225, in endereco_emitente_formatado_linha_3
    if formata_fone(NFe.infNFe.emit.enderEmit.fone).strip() != '':
  File "/odoo-lab/venv37/lib/python3.8/site-packages/erpbrasil/edoc/pdf/danfe_formata.py", line 53, in formata_fone
    if not len(fone.strip()):
TypeError: 'VoidElement' object is not callable

cc @mileo @luismalta @gabrielcardoso21

**Comment by gabrielcardoso21** [comment]
Fiz um commit agora na master dessa biblioteca. Vê se corrigiu, por favor.

**Comment by marcelsavegnago** [comment]
@gabrielcardoso21 Aparentemente não deu certo não.

```
erpbrasil/edoc/pdf/danfe_formata.py", line 53, in formata_fone
    if not fone and not len(fone.strip()):
TypeError: 'VoidElement' object is not callable
```

**Comment by marcelsavegnago** [comment]
@gabrielcardoso21 a alteração será que não deve ser feita aqui ? 
https://github.com/erpbrasil/erpbrasil.edoc.pdf/blob/e1e55bcbadc4eef3c9b5a7551d205c99f3aa329d/src/erpbrasil/edoc/pdf/danfe_formata.py#L225

**Comment by gabrielcardoso21** [comment]
Foi erro de lógica aqui. Tinha que ser um or. Atualizei na biblioteca, tenta de novo, por favor.

**Comment by marcelsavegnago** [comment]
> Foi erro de lógica aqui. Tinha que ser um or. Atualizei na biblioteca, tenta de novo, por favor.

Perfeito. Vlwww

**Comment by marcelsavegnago** [comment]
@gabrielcardoso21 acho que agora soh precisa atualizar no pypi neh ?

**Comment by gabrielcardoso21** [comment]
Sim, vou ver com o mileo aqui como faço isso.

**Comment by gabrielcardoso21** [comment]
https://pypi.org/project/erpbrasil.edoc.pdf/0.0.1/
@marcelsavegnago

**Comment by marcelsavegnago** [comment]
@gabrielcardoso21 blzz.. to esperando acertar a branch 12.0 e faço uma PR já atualizando o requirements da OCA.

Pelo que vi estava na versão 0.1.0 e agora ficou 0.0.1 ?

**Comment by gabrielcardoso21** [comment]
@marcelsavegnago corrigi: https://pypi.org/manage/project/erpbrasil.edoc.pdf/release/0.1.1/
